steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/sklearn-usedcars-extratrees:latest', './train']

images:
-  'gcr.io/$PROJECT_ID/sklearn-usedcars-extratrees:latest'